### PR TITLE
fixed spelling error in IDE entry of glossary

### PR DESCRIPTION
**Pull request by pixelpollux**

### CODE REVIEW

**Comment by pixelpollux** [comment]
addresses #12 IDE listing in the Glossary is misspelled

- [ ] corrected spelling of glossary item

- [ ] updated link under glossary item

**Review by pixelpollux — COMMENTED** [review]
addresses #11 Each link in Validation tools section should be in its own line

- [ ] put in line breaks for links in validation section

**Review by alisaduncan — APPROVED** [review]

**Comment by alisaduncan** [comment]
Fixes #12

**Pull request merged**
